/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lucas
 */
public class PlataformaMapa extends javax.swing.JFrame {

    Senha senha = new Senha();
    
    public PlataformaMapa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        campoSenha = new java.awt.Label();
        caixachamado = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        suasenha = new java.awt.TextField();
        bcomum = new java.awt.Button();
        brapido = new java.awt.Button();
        bpreferencial = new java.awt.Button();
        caixa1 = new java.awt.Button();
        caixa2 = new java.awt.Button();
        caixa3 = new java.awt.Button();
        caixa4 = new java.awt.Button();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        campoSenha.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        campoSenha.setText("teste");

        caixachamado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        caixachamado.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        caixachamado.setText("teste");

        label3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label3.setText("Escolha seu Tipo de atendimento");

        label4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label4.setText("Atendimento - Caixas");

        suasenha.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        suasenha.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        suasenha.setName(""); // NOI18N
        suasenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suasenhaActionPerformed(evt);
            }
        });

        bcomum.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bcomum.setLabel("Comum");
        bcomum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcomumActionPerformed(evt);
            }
        });

        brapido.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        brapido.setLabel("Rápido");
        brapido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brapidoActionPerformed(evt);
            }
        });

        bpreferencial.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bpreferencial.setLabel("Preferencial");
        bpreferencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpreferencialActionPerformed(evt);
            }
        });

        caixa1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        caixa1.setLabel("Caixa 1");
        caixa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixa1ActionPerformed(evt);
            }
        });

        caixa2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        caixa2.setLabel("Caixa 2");
        caixa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixa2ActionPerformed(evt);
            }
        });

        caixa3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        caixa3.setLabel("Caixa 3");
        caixa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixa3ActionPerformed(evt);
            }
        });

        caixa4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        caixa4.setLabel("Caixa 4");
        caixa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixa4ActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setText("Atendimento - Senhas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(bcomum, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(suasenha, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(205, 205, 205)
                                .addComponent(caixa3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(brapido, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bpreferencial, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(caixa1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(caixa4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(caixa2, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(caixachamado, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caixachamado, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(caixa2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(caixa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(brapido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bcomum, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(bpreferencial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(caixa4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(suasenha, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caixa3, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bcomumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcomumActionPerformed
        senha.numero++;
        senha.tipo = "C";
        senha.lista.add(senha.tipo + " - " + senha.numero);
        suasenha.setText(senha.tipo + " - " + senha.numero);
    }//GEN-LAST:event_bcomumActionPerformed

    private void brapidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brapidoActionPerformed
        senha.numero++;
        senha.tipo = "R";
        senha.lista.add(senha.tipo + " - " + senha.numero);
        suasenha.setText(senha.tipo + " - " + senha.numero);
    }//GEN-LAST:event_brapidoActionPerformed

    private void caixa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixa1ActionPerformed
        if(senha.lista.size()>0){
            caixachamado.setText("Caixa 1");
        }
        if (senha.lista.toString().contains("P")) {
            for (String fila : senha.lista) {
                if(fila.contains("P")){
                   campoSenha.setText(fila);
                   senha.lista.remove(fila);
                   break;
                }
            }
        }else{
            for (String fila : senha.lista) {
                   campoSenha.setText(fila);
                   senha.lista.remove(fila);
                   break;
            }
        }
    }//GEN-LAST:event_caixa1ActionPerformed

    private void bpreferencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpreferencialActionPerformed
        senha.numero++;
        senha.tipo = "P";
        senha.lista.add(senha.tipo + " - " + senha.numero);
        suasenha.setText(senha.tipo + " - " + senha.numero);
    }//GEN-LAST:event_bpreferencialActionPerformed

    private void caixa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixa2ActionPerformed
        if(senha.lista.size()>0) {
            caixachamado.setText("Caixa 2");
        }   
        if(senha.lista.toString().contains("R")){
            for (String fila : senha.lista) {
                if(fila.contains("R")) {
                    campoSenha.setText(fila);
                    senha.lista.remove(fila);
                    break;
                }
            }
        }else{
            for (String fila : senha.lista) {
                   campoSenha.setText(fila);
                   senha.lista.remove(fila);
                   break;
        }
    }//GEN-LAST:event_caixa2ActionPerformed
    }
    private void caixa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixa3ActionPerformed
         if(senha.lista.size()>0) {
            caixachamado.setText("Caixa 3");
        }   
        if(senha.lista.toString().contains("R")){
            for (String fila : senha.lista) {
                if(fila.contains("R")) {
                    campoSenha.setText(fila);
                    senha.lista.remove(fila);
                    break;
                }
            }
        }else{
            for (String fila : senha.lista) {
                   campoSenha.setText(fila);
                   senha.lista.remove(fila);
                   break;
            }
        }
    }//GEN-LAST:event_caixa3ActionPerformed

    private void caixa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixa4ActionPerformed
        if(senha.lista.size()>0) {
            caixachamado.setText("Caixa 4");
        }   
        if(senha.lista.toString().contains("C")){
            for (String fila : senha.lista) {
                if(fila.contains("C")) {
                    campoSenha.setText(fila);
                    senha.lista.remove(fila);
                    break;
                }
            }
        }else{
            for (String fila : senha.lista) {
                   campoSenha.setText(fila);
                   senha.lista.remove(fila);
                   break;
            }
        }
    }//GEN-LAST:event_caixa4ActionPerformed

    private void suasenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suasenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suasenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlataformaMapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlataformaMapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlataformaMapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlataformaMapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlataformaMapa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button bcomum;
    private java.awt.Button bpreferencial;
    private java.awt.Button brapido;
    private java.awt.Button caixa1;
    private java.awt.Button caixa2;
    private java.awt.Button caixa3;
    private java.awt.Button caixa4;
    private java.awt.Label caixachamado;
    private java.awt.Label campoSenha;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.TextField suasenha;
    // End of variables declaration//GEN-END:variables
}
